# Generated by Django 3.2.20 on 2023-07-12 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runplan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='isPast',
        ),
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
